-- ACCOUNT_USER TABLE CREATION
DROP TABLE IF EXISTS ACCOUNT_USER;
CREATE TABLE ACCOUNT_USER (
   ID INT NOT NULL,
   NAME VARCHAR(50),
   ADDRESS VARCHAR(500),
   CREATED_DT datetime,
   LAST_UPDATED_DT datetime
);
ALTER TABLE ACCOUNT_USER ADD CONSTRAINT ACCOUNT_USER_PK PRIMARY KEY(ID);

-- ACCOUNT TABLE CREATION
DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
   ID INT NOT NULL,
   ACCOUNT_OWNER_ID INT NOT NULL,
   ACCOUNT_NUMBER NUMBER(11) NOT NULL,
   BALANCE DECIMAL(10,2) NOT NULL,
   CURRENCY_CODE VARCHAR(3) NOT NULL,,
   CREATED_DT datetime,
   LAST_UPDATED_DT datetime,
   FOREIGN KEY(ACCOUNT_OWNER_ID) REFERENCES ACCOUNT_USER(ID)
);
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY(ID);

-- TRANSFER TABLE CREATION
DROP TABLE IF EXISTS TRANSFER;
CREATE TABLE TRANSFER (
   ID INT NOT NULL,
   FROM_ACCOUNT_NO NUMBER(11) NOT NULL,
   TO_ACCOUNT_NO NUMBER(11) NOT NULL,
   AMOUNT DECIMAL(10,2) NOT NULL,
   CURRENCY_CODE VARCHAR(3) NOT NULL,
   STATUS VARCHAR(20) NOT NULL,
   REMARKS VARCHAR(100),
   CREATED_DT datetime,
   LAST_UPDATED_DT datetime,
   FOREIGN KEY(FROM_ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NUMBER),
   FOREIGN KEY(TO_ACCOUNT_NO) REFERENCES ACCOUNT(ACCOUNT_NUMBER)
);
ALTER TABLE TRANSFER ADD CONSTRAINT TRANSFER_PK PRIMARY KEY(ID);

-- CREATE SEQUENCES
DROP SEQUENCE IF EXISTS TRANSFER_SEQ;
CREATE SEQUENCE TRANSFER_SEQ
    START WITH 1
    INCREMENT BY 1;

DROP SEQUENCE IF EXISTS ACCOUNT_SEQ;
CREATE SEQUENCE ACCOUNT_SEQ
    START WITH 1
    INCREMENT BY 1;


DROP SEQUENCE IF EXISTS ACCOUNT_USER_SEQ;
CREATE SEQUENCE ACCOUNT_USER_SEQ
    START WITH 1
    INCREMENT BY 1;

COMMIT;

-- ACCOUNT_USER TABLE DATA POPULATION
INSERT INTO ACCOUNT_USER values (ACCOUNT_USER_SEQ.nextVal, 'Fortun Allaire', '68, place Maurice-Charretier 08000 CHARLEVILLE-MEZIERES', SYSDATE, null);
INSERT INTO ACCOUNT_USER values (ACCOUNT_USER_SEQ.nextVal, 'Nadia R. Odell', '2807 Lakewood Drive Englewood, NJ 07631', SYSDATE, null);
INSERT INTO ACCOUNT_USER values (ACCOUNT_USER_SEQ.nextVal, 'Melusina Tan', '71 Wilkie Road 228071 Singapore', SYSDATE, null);
INSERT INTO ACCOUNT_USER values (ACCOUNT_USER_SEQ.nextVal, 'Ella Raiwala', '91 Glen William Road GERMANTOWN QLD 4871', SYSDATE, null);
INSERT INTO ACCOUNT_USER values (ACCOUNT_USER_SEQ.nextVal, 'Jeanne Deblois', '84, Cours Marechal-Joffre 76200 DIEPPE', SYSDATE, null);
INSERT INTO ACCOUNT_USER values (ACCOUNT_USER_SEQ.nextVal, 'Gioacchino Nucci', 'Gartenhof 117 1321 Arnex-sur-Orbe', SYSDATE, null);

-- ACCOUNT TABLE DATA POPULATION
INSERT INTO ACCOUNT values (ACCOUNT_SEQ.nextVal, 1, 12345678901, 500.57, 'EUR', SYSDATE, null);
INSERT INTO ACCOUNT values (ACCOUNT_SEQ.nextVal, 2, 23456789012, 909.40, 'USD', SYSDATE, null);
INSERT INTO ACCOUNT values (ACCOUNT_SEQ.nextVal, 3, 34567890123, 767.26, 'SGD', SYSDATE, null);
INSERT INTO ACCOUNT values (ACCOUNT_SEQ.nextVal, 4, 45678901234, 1493.60, 'AUD', SYSDATE, null);
INSERT INTO ACCOUNT values (ACCOUNT_SEQ.nextVal, 5, 56789012345, 1171.06, 'EUR', SYSDATE, null);
INSERT INTO ACCOUNT values (ACCOUNT_SEQ.nextVal, 6, 67890123456, 902.99, 'CHF', SYSDATE, null);
INSERT INTO ACCOUNT values (ACCOUNT_SEQ.nextVal, 1, 78901234567, 1226.15, 'EUR', SYSDATE, null);
INSERT INTO ACCOUNT values (ACCOUNT_SEQ.nextVal, 3, 89012345678, 289.88, 'SGD', SYSDATE, null);
INSERT INTO ACCOUNT values (ACCOUNT_SEQ.nextVal, 5, 90123456789, 1673.94, 'EUR', SYSDATE, null);
INSERT INTO ACCOUNT values (ACCOUNT_SEQ.nextVal, 1, 01234567890, 1351.12, 'EUR', SYSDATE, null);



INSERT INTO TRANSFER values (TRANSFER_SEQ.nextVal, 12345678901, 56789012345, 123.12,'EUR', 'PROCESSED', null, TO_DATE('20180510 102359','YYYYMMDD HH24MISS'), TO_DATE('20180510 102523','YYYYMMDD HH24MISS'));


COMMIT;